[tool.poetry]
name = "Environments"
version = "0.1.0"
description = "Testing"
authors = []

[tool.poetry.dependencies]
python = "^3.8"
emoji = "^2.0.0"
print-color = "^0.4.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
